name: CI Workflow with Codecov

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - unlocked

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgres://postgres:DO_NOT_USE_THIS_PASSWORD_IN_PRODUCTION@db:5432/test_db"
      APP_ENV: "test"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Install pipenv
        run: pip install pipenv

      - name: Install project dependencies
        run: make install-deps

      - name: Run docker-compose up
        run: make docker-up option=-d

      - name: Run tests with coverage
        run: make test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./src/coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml # Optional
